sources:
# - name: brown_university
#   root_url: https://bulletin.brown.edu/
#   schema_url: https://bulletin.brown.edu/biologyandmedicine/biology-undergraduate/#courseinventory
#   type: "html"
#   crawl_depth: 3

# - name: massachusetts_institute_of_technology
#   root_url: https://catalog.mit.edu/
#   schema_url: https://catalog.mit.edu/search/?P=4.023
#   type: "html"
#   crawl_depth: 8

# - name: purdue_university
#   root_url: https://catalog.purdue.edu/content.php?catoid=7&navoid=2928
#   schema_url: https://catalog.purdue.edu/preview_course_nopop.php?catoid=7&coid=50181
#   type: "html"
#   crawl_depth: 80
#   include_external: True

# - name: yale_university
#   root_url: https://catalog.yale.edu/ycps/courses/
#   schema_url: https://catalog.yale.edu/ycps/courses/cpsc/
#   type: "html"
#   crawl_depth: 4

# CAN REQUEST FOR COURSES DIRECTLY IF NEEDED
# - name: florida_state_university
#   root_url: https://catalog.fsu.edu/             # FSU catalog homepage 
#   schema_url: https://catalog.fsu.edu/preview_course.php?catoid=24&coid=26268  # Example course page 
#   type: "html"
#   crawl_depth: 3

# - name: duke_university
#   root_url: https://registrar.duke.edu/bulletins/
#   schema_url: https://undergraduate.bulletins.duke.edu/courses/0292481
#   type: "html"
#   crawl_depth: 500

# - name: rice_university
#   root_url: https://courses.rice.edu/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr_code=2025
#   schema_url: https://courses.rice.edu/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr_code=2025&p_crse_numb=110&p_subj=AAAS
#   type: "html"
#   crawl_depth: 2
#   include_external: True

# - name: university_of_florida
#   root_url: https://catalog.ufl.edu/
#   schema_url: https://catalog.ufl.edu/UGRD/courses/african_american_studies/
#   type: "html"
#   crawl_depth: 4

- name: texas_a_and_m_university
  root_url: https://catalog.tamu.edu/
  schema_url: https://catalog.tamu.edu/undergraduate/business/management/#coursestext
  type: "html"
  crawl_depth: 6

# - name: iowa_state_university
#   root_url: https://catalog.iastate.edu/
#   schema_url: https://catalog.iastate.edu/azcourses/acct/
#   type: "html"
#   crawl_depth: 3

# - name: university_of_minnesota_twin_cities
#   root_url: https://catalogs.umn.edu/
#   schema_url: https://umc.catalog.prod.coursedog.com/courses?page=1&cq=
#   type: "html"
#   crawl_depth: 3
#   include_external: True