sources:
- name: brown_university
  root_url: https://bulletin.brown.edu/
  schema_url: https://bulletin.brown.edu/biologyandmedicine/biology-undergraduate/#courseinventory
  type: html
  max_concurrency: 1
  url_exclude_patterns: ["search", "azindex"]

# - name: massachusetts_institute_of_technology
#   root_url: https://catalog.mit.edu/
#   schema_url: https://catalog.mit.edu/search/?P=4.023
#   type: "html"
#   crawl_depth: 8

# - name: purdue_university
#   root_url: https://catalog.purdue.edu/content.php?catoid=7&navoid=2928
#   schema_url: https://catalog.purdue.edu/preview_course_nopop.php?catoid=7&coid=50181
#   type: "html"
#   crawl_depth: 80
#   include_external: True

# - name: yale_university
#   root_url: https://catalog.yale.edu/ycps/courses/
#   schema_url: https://catalog.yale.edu/ycps/courses/cpsc/
#   type: "html"
#   crawl_depth: 4

# CAN REQUEST FOR COURSES DIRECTLY IF NEEDED
# - name: florida_state_university
#   root_url: https://catalog.fsu.edu/             # FSU catalog homepage 
#   schema_url: https://catalog.fsu.edu/preview_course.php?catoid=24&coid=26268  # Example course page 
#   type: "html"
#   crawl_depth: 3

# - name: duke_university
#   root_url: https://registrar.duke.edu/bulletins/
#   schema_url: https://undergraduate.bulletins.duke.edu/courses/0292481
#   type: "html"
#   crawl_depth: 500

# - name: rice_university
#   root_url: https://courses.rice.edu/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr_code=2025
#   schema_url: https://courses.rice.edu/courses/!SWKSCAT.cat?p_action=CATALIST&p_acyr_code=2025&p_crse_numb=110&p_subj=AAAS
#   type: "html"
#   crawl_depth: 2
#   include_external: True

# - name: university_of_florida
#   root_url: https://catalog.ufl.edu/
#   schema_url: https://catalog.ufl.edu/UGRD/courses/african_american_studies/
#   type: "html"
#   crawl_depth: 4

- name: texas_a_and_m_university
  root_url: https://catalog.tamu.edu/
  schema_url: https://catalog.tamu.edu/undergraduate/business/management/#coursestext
  type: "html"
  crawl_depth: 3
  max_concurrency: 1
  url_exclude_patterns: ["search"]

- name: california_institute_of_technology
  root_url: https://www.catalog.caltech.edu/current/2024-25/
  schema_url: https://www.catalog.caltech.edu/current/2024-25/department/Ae/
  type: html
  max_concurrency: 1
  crawl_depth: 3

- name: university_of_houston_undergraduate
  root_url: https://publications.uh.edu/content.php?catoid=52&navoid=19813
  schema_url: https://publications.uh.edu/preview_course_nopop.php?catoid=52&coid=271554
  url_base_exclude: https://publications.uh.edu
  max_concurrency: 1
  crawl_depth: 43

- name: university_of_houston_graduate
  root_url: https://publications.uh.edu/content.php?catoid=53&navoid=20423
  schema_url: https://publications.uh.edu/preview_course_nopop.php?catoid=53&coid=279846
  url_base_exclude: https://publications.uh.edu
  max_concurrency: 1
  crawl_depth: 46

- name: appalachian_state_university_undergraduate
  root_url: https://bulletin.appstate.edu/content.php?catoid=39&navoid=2430
  schema_url: https://bulletin.appstate.edu/preview_course_nopop.php?catoid=39&coid=139133
  url_base_exclude: https://bulletin.appstate.edu
  max_concurrency: 1
  crawl_depth: 36

- name: appalachian_state_university_graduate
  root_url: https://bulletin.appstate.edu/content.php?catoid=33&navoid=2058
  schema_url: https://bulletin.appstate.edu/preview_course_nopop.php?catoid=33&coid=119819
  url_base_exclude: https://bulletin.appstate.edu
  max_concurrency: 1
  crawl_depth: 17

- name: louisiana_state_university
  root_url: https://catalog.lsu.edu/content.php?catoid=33&navoid=3206
  schema_url: https://catalog.lsu.edu/preview_course_nopop.php?catoid=33&coid=224102
  url_base_exclude: https://catalog.lsu.edu
  max_concurrency: 1
  crawl_depth: 61

- name: morgan_state_university_undergraduate
  root_url: https://catalog.morgan.edu/content.php?catoid=26&navoid=1881
  schema_url: https://catalog.morgan.edu/preview_course_nopop.php?catoid=26&coid=57239
  url_base_exclude: https://catalog.morgan.edu
  max_concurrency: 1
  crawl_depth: 22
  
- name: morgan_state_university_graduate
  root_url: https://catalog.morgan.edu/content.php?catoid=27&navoid=1991
  schema_url: https://catalog.morgan.edu/preview_course_nopop.php?catoid=27&coid=61591
  url_base_exclude: https://catalog.morgan.edu
  max_concurrency: 1
  crawl_depth: 19

- name: tuskegee_university
  root_url: https://catalog.tuskegee.edu/content.php?catoid=15&navoid=849
  schema_url: https://catalog.tuskegee.edu/preview_course_nopop.php?catoid=15&coid=26801
  url_base_exclude: https://catalog.tuskegee.edu
  max_concurrency: 1
  crawl_depth: 19

- name: western_michigan_university_undergraduate
  root_url: https://catalog.wmich.edu/content.php?catoid=45&navoid=2169
  schema_url: https://catalog.wmich.edu/preview_course_nopop.php?catoid=45&coid=138571
  url_base_exclude: https://catalog.wmich.edu
  max_concurrency: 1
  crawl_depth: 30

- name: western_michigan_university_graduate
  root_url: https://catalog.wmich.edu/content.php?catoid=46&navoid=2230
  schema_url: https://catalog.wmich.edu/preview_course_nopop.php?catoid=46&coid=144223
  url_base_exclude: https://catalog.wmich.edu
  max_concurrency: 1
  crawl_depth: 22

- name: adams_state_university
  root_url: https://adams.catalog.acalog.com/content.php?catoid=76&navoid=4847
  schema_url: https://adams.catalog.acalog.com/preview_course_nopop.php?catoid=76&coid=166804
  url_base_exclude: https://adams.catalog.acalog.com
  max_concurrency: 1
  crawl_depth: 17


# - name: iowa_state_university
#   root_url: https://catalog.iastate.edu/
#   schema_url: https://catalog.iastate.edu/azcourses/acct/
#   type: "html"
#   crawl_depth: 3

# - name: university_of_minnesota_twin_cities
#   root_url: https://catalogs.umn.edu/
#   schema_url: https://umc.catalog.prod.coursedog.com/courses?page=1&cq=
#   type: "html"
#   crawl_depth: 3
#   include_external: True