sources:
- source_id: LOCAL_Oregon State University
  name: Oregon State University
  root_url: https://catalog.oregonstate.edu/courses/
  schema_url: https://catalog.oregonstate.edu/courses/art/321/
